/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package ru.arch.cinemaabyss.proxy.api

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import jakarta.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import ru.arch.cinemaabyss.proxy.api.model.*

@Validated
@RequestMapping("\${api.base-path:}")
interface EventsApi {

    @Operation(
        summary = "Создание события фильма",
        operationId = "createMovieEvent",
        description = """Регистрирует новое событие, связанное с фильмом""",
        responses = [
            ApiResponse(responseCode = "201", description = "Событие успешно создано", content = [Content(schema = Schema(implementation = EventResponse::class))]),
            ApiResponse(responseCode = "400", description = "Некорректный запрос", content = [Content(schema = Schema(implementation = Error::class))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/events/movie"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createMovieEvent(@Parameter(description = "Данные события фильма", required = true) @Valid @RequestBody movieEvent: MovieEvent): ResponseEntity<EventResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Создание события платежа",
        operationId = "createPaymentEvent",
        description = """Регистрирует новое событие, связанное с платежом""",
        responses = [
            ApiResponse(responseCode = "201", description = "Событие успешно создано", content = [Content(schema = Schema(implementation = EventResponse::class))]),
            ApiResponse(responseCode = "400", description = "Некорректный запрос", content = [Content(schema = Schema(implementation = Error::class))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/events/payment"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createPaymentEvent(@Parameter(description = "Данные события платежа", required = true) @Valid @RequestBody paymentEvent: PaymentEvent): ResponseEntity<EventResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Создание события пользователя",
        operationId = "createUserEvent",
        description = """Регистрирует новое событие, связанное с пользователем""",
        responses = [
            ApiResponse(responseCode = "201", description = "Событие успешно создано", content = [Content(schema = Schema(implementation = EventResponse::class))]),
            ApiResponse(responseCode = "400", description = "Некорректный запрос", content = [Content(schema = Schema(implementation = Error::class))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/events/user"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createUserEvent(@Parameter(description = "Данные события пользователя", required = true) @Valid @RequestBody userEvent: UserEvent): ResponseEntity<EventResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
