/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package ru.arch.cinemaabyss.proxy.api

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import ru.arch.cinemaabyss.proxy.api.model.GetMoviesServiceHealth200Response

@Validated
@RequestMapping("\${api.base-path:}")
interface HealthApi {

    @Operation(
        tags = ["health",],
        summary = "Проверка работоспособности микросервиса событий",
        operationId = "getEventsServiceHealth",
        description = """Возвращает статус работоспособности микросервиса событий""",
        responses = [
            ApiResponse(responseCode = "200", description = "Успешный ответ", content = [Content(schema = Schema(implementation = GetMoviesServiceHealth200Response::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/events/health"],
            produces = ["application/json"]
    )
    fun getEventsServiceHealth(): ResponseEntity<GetMoviesServiceHealth200Response> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["health",],
        summary = "Проверка работоспособности микросервиса фильмов",
        operationId = "getMoviesServiceHealth",
        description = """Возвращает статус работоспособности микросервиса фильмов""",
        responses = [
            ApiResponse(responseCode = "200", description = "Успешный ответ", content = [Content(schema = Schema(implementation = GetMoviesServiceHealth200Response::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/movies/health"],
            produces = ["application/json"]
    )
    fun getMoviesServiceHealth(): ResponseEntity<GetMoviesServiceHealth200Response> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["health",],
        summary = "Проверка работоспособности API Gateway",
        operationId = "getProxyHealth",
        description = """Возвращает статус работоспособности прокси-сервиса""",
        responses = [
            ApiResponse(responseCode = "200", description = "Успешный ответ", content = [Content(schema = Schema(implementation = kotlin.String::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/health"],
            produces = ["text/plain"]
    )
    fun getProxyHealth(): ResponseEntity<kotlin.String> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
