/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package ru.arch.cinemaabyss.proxy.api

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.media.ArraySchema
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import jakarta.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import ru.arch.cinemaabyss.proxy.api.model.Error
import ru.arch.cinemaabyss.proxy.api.model.Movie
import ru.arch.cinemaabyss.proxy.api.model.MovieInput

@Validated
@RequestMapping("\${api.base-path:}")
interface MoviesApi {

    @Operation(
        tags = ["movies",],
        summary = "Создание нового фильма",
        operationId = "createMovie",
        description = """Добавляет новый фильм в систему""",
        responses = [
            ApiResponse(responseCode = "201", description = "Фильм успешно создан", content = [Content(schema = Schema(implementation = Movie::class))]),
            ApiResponse(responseCode = "400", description = "Некорректный запрос", content = [Content(schema = Schema(implementation = Error::class))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/movies"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createMovie(@Parameter(description = "Данные фильма для создания", required = true) @Valid @RequestBody movieInput: MovieInput): ResponseEntity<Movie> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["movies",],
        summary = "Получение списка всех фильмов",
        operationId = "getAllMovies",
        description = """Возвращает список всех фильмов с их метаданными""",
        responses = [
            ApiResponse(responseCode = "200", description = "Успешный ответ", content = [Content(array = ArraySchema(schema = Schema(implementation = Movie::class)))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/movies"],
            produces = ["application/json"]
    )
    fun getAllMovies(): ResponseEntity<List<Movie>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
