/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package ru.arch.cinemaabyss.proxy.api

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.media.ArraySchema
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import jakarta.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import ru.arch.cinemaabyss.proxy.api.model.Error
import ru.arch.cinemaabyss.proxy.api.model.User
import ru.arch.cinemaabyss.proxy.api.model.UserInput

@Validated
@RequestMapping("\${api.base-path:}")
interface UsersApi {

    @Operation(
        tags = ["users",],
        summary = "Создание нового пользователя",
        operationId = "createUser",
        description = """Регистрирует нового пользователя в системе""",
        responses = [
            ApiResponse(responseCode = "201", description = "Пользователь успешно создан", content = [Content(schema = Schema(implementation = User::class))]),
            ApiResponse(responseCode = "400", description = "Некорректный запрос", content = [Content(schema = Schema(implementation = Error::class))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/users"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createUser(@Parameter(description = "Данные пользователя для создания", required = true) @Valid @RequestBody userInput: UserInput): ResponseEntity<User> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["users",],
        summary = "Получение списка всех пользователей",
        operationId = "getAllUsers",
        description = """Возвращает список всех пользователей системы""",
        responses = [
            ApiResponse(responseCode = "200", description = "Успешный ответ", content = [Content(array = ArraySchema(schema = Schema(implementation = User::class)))]),
            ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = [Content(schema = Schema(implementation = Error::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/users"],
            produces = ["application/json"]
    )
    fun getAllUsers(): ResponseEntity<List<User>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
